<?php

namespace Database\Seeders;

use App\Models\Disclaimer as ModelsDisclaimer;
use App\Models\UserGuide;
use Illuminate\Database\Seeder;

class Disclaimer extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ModelsDisclaimer::create([
            'disclaimer' => '<p><strong>If you do not agree to the Terms of Use, discontinue using the site immediately!</strong></p>
            <p>The http://www.myeasygoals.com Web Site (the "Site") is an online information service provided by TD McKenzie Training ("http://www.myeasygoals.com "), subject to your compliance with the terms and conditions set forth below. PLEASE READ THIS DOCUMENT CAREFULLY BEFORE ACCESSING OR USING THE SITE. BY ACCESSING OR USING THE SITE, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS AND CONDITIONS, YOU MAY NOT ACCESS OR USE THE SITE. http://www.myeasygoals.com MAY MODIFY THIS AGREEMENT AT ANY TIME, AND SUCH MODIFICATIONS SHALL BE EFFECTIVE IMMEDIATELY UPON POSTING OF THE MODIFIED AGREEMENT ON THE SITE. YOU AGREE TO REVIEW THE AGREEMENT PERIODICALLY TO BE AWARE OF SUCH MODIFICATIONS AND YOUR CONTINUED ACCESS OR USE OF THE SITE SHALL BE DEEMED YOUR CONCLUSIVE ACCEPTANCE OF THE MODIFIED AGREEMENT.</p>
            <p><strong>1. Copyright, Licenses, and Idea Submissions.</strong></p>
            <p>The entire contents of the Site are protected by international copyright and trademark laws. The owner of the copyrights and trademarks are http://www.myeasygoals.com, its affiliates or other third party licensors. YOU MAY NOT MODIFY, COPY, REPRODUCE, REPUBLISH, UPLOAD, POST, TRANSMIT, OR DISTRIBUTE, IN ANY MANNER, THE MATERIAL ON THE SITE, INCLUDING TEXT, GRAPHICS, CODE AND/OR SOFTWARE. You may print and download portions of material from the different areas of the Site solely for your own non-commercial use provided that you agree not to change or delete any copyright or proprietary notices from the materials. You agree to grant to http://www.myeasygoals.com a non-exclusive, royalty-free, worldwide, perpetual license, with the right to sub-license, to reproduce, distribute, transmit, create derivative works of, publicly display and publicly perform any materials and other information (including, without limitation, ideas contained therein for new or improved products and services) you submit to any public areas of the Site (such as bulletin boards, forums and newsgroups) or by e-mail to http://www.myeasygoals.com by all means and in any media now known or hereafter developed. You also grant to http://www.myeasygoals.com the right to use your name in connection with the submitted materials and other information as well as in connection with all advertising, marketing and promotional material related thereto. You agree that you shall have no recourse against http://www.myeasygoals.com for any alleged or actual infringement or misappropriation of any proprietary right in your communications to http://www.myeasygoals.com.</p>
            <p><strong>TRADEMARKS</strong></p>
            <p>Publications, products, content, or services referenced herein or on the Site are the exclusive trademarks or service marks of http://www.myeasygoals.com. Other product and company names mentioned in the Site may be the trademarks of their respective owners.</p>
            <p><strong>2. Use of the Site.</strong></p>
            <p>You understand that, except for information, products or services clearly identified as being supplied by http://www.myeasygoals.com, http://www.myeasygoals.com does not operate, control, or endorse any information, products or services on the Internet in any way. Except for http://www.myeasygoals.com- identified information, products or services, all information, products, and services offered through the Site or on the Internet generally are offered by third parties, that are not affiliated with http://www.myeasygoals.com a. You also understand that http://www.myeasygoals.com cannot and does not guarantee or warrant that files available for downloading through the Site will be free of infection or viruses, worms, Trojan horses, or other code that manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for accuracy of data input and output, and for maintaining a means external to the Site for the reconstruction of any lost data.</p>
            <p>YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND THE INTERNET. http://www.myeasygoals.com PROVIDES THE SITE AND RELATED INFORMATION "AS IS" AND DOES NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES, REPRESENTATIONS OR ENDORSEMENTS WHATSOEVER (INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE OR NONINFRINGEMENT, OR THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE) WITH REGARD TO THE SERVICE, ANY MERCHANDISE INFORMATION OR SERVICE PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY, AND http://www.myeasygoals.com SHALL NOT BE LIABLE FOR ANY COST OR DAMAGE ARISING EITHER DIRECTLY OR INDIRECTLY FROM ANY SUCH TRANSACTION. IT IS SOLELY YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ALL OPINIONS, ADVICE, SERVICES, MERCHANDISE AND OTHER INFORMATION PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY. http://www.myeasygoals.com DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED.<br>YOU UNDERSTAND FURTHER THAT THE PURE NATURE OF THE INTERNET CONTAINS UNEDITED MATERIALS, SOME OF WHICH ARE SEXUALLY EXPLICIT OR MAY BE OFFENSIVE TO YOU. YOUR ACCESS TO SUCH MATERIALS IS AT YOUR OWN RISK. http://www.myeasygoals.com HAS NO CONTROL OVER AND ACCEPTS NO RESPONSIBILITY WHATSOEVER FOR SUCH MATERIALS.</p>
            <p><strong>LIMITATION OF LIABILITY</strong></p>
            <p>IN NO EVENT WILL http://www.myeasygoals.com BE LIABLE FOR (I) ANY INCIDENTAL, CONSEQUENTIAL, OR INDIRECT DAMAGES (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR INFORMATION, AND THE LIKE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICE, OR ANY INFORMATION, OR TRANSACTIONS PROVIDED ON THE SERVICE, OR DOWNLOADED FROM THE SERVICE, OR ANY DELAY OF SUCH INFORMATION OR SERVICE. EVEN IF http://www.myeasygoals.com OR ITS AUTHORIZED REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR (II) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN THE SERVICE AND/OR MATERIALS OR INFORMATION DOWNLOADED THROUGH THE SERVICE. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, http://www.myeasygoals.com LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.<br>http://www.myeasygoals.com makes no representations whatsoever about any other website which you may access through this one or which may link to this Site. When you access a non-http://www.myeasygoals.com web site, please understand that it is independent from http://www.myeasygoals.com, and that http://www.myeasygoals.com has no control over the content on that web site. In addition, a link to a http://www.myeasygoals.com web site does not mean that http://www.myeasygoals.com endorses or accepts any responsibility for the content, or the use, of such web site.</p>
            <p><strong>3. Indemnification.</strong></p>
            <p>You agree to indemnify, defend and hold harmless http://www.myeasygoals.com, its officers, directors, employees, agents, licensors, suppliers and any third party information providers to the Service from and against all losses, expenses, damages and costs, including reasonable attorneys" fees, resulting from any violation of this Agreement (including negligent or wrongful conduct) by you or any other person accessing the Service.</p>
            <p><strong>4. Third Party Rights.</strong></p>
            <p>The provisions of paragraphs 2 (Use of the Service), and 3 (Indemnification) are for the benefit of http://www.myeasygoals.com and its officers, directors, employees, agents, licensors, suppliers, and any third party information providers to the Service. Each of these individuals or entities shall have the right to assert and enforce those provisions directly against you on its own behalf.</p>
            <p><strong>5. Term; Termination.</strong></p>
            <p>This Agreement may be terminated by either party without notice at any time for any reason. The provisions of paragraphs 1 (Copyright, Licenses, and Idea Submissions), 2 (Use of the Service), 3 (Indemnification), 4 (Third Party Rights) and 6 (Miscellaneous) shall survive any termination of this Agreement.</p>
            <p><strong>6. Database Ownership, License, and Use</strong></p>
            <p>http://www.myeasygoals.com warrants, and you accept, that My Easy Goals&trade; is the owner of the copyright of the Databases of Links to articles and resources available from time to time My Easy Goals&trade; and its contributors reserve all rights and no intellectual property rights are conferred by this agreement.<br>http://www.myeasygoals.com grants you a non-exclusive, non-transferable license to use database(s) accessible to you subject to these Terms and Conditions. The database(s) may be used only for viewing or listening to information or for extracting information to the extent described below.<br>You agree to use information obtained from http://www.myeasygoals.com databases only for your own private use or the internal purposes of your home or business, provided that is not the selling or broking of information, and in no event cause or permit to be published, printed, downloaded, transmitted, distributed, reengineered, or reproduced in any form any part of the databases (whether directly or in condensed, selective or tabulated form) whether for resale, republishing, redistribution, viewing, or otherwise.</p>
            <p>Nevertheless, you may on an occasional limited basis download or print out individual pages of information that have been individually selected, to meet a specific, identifiable need for information which is for your personal use only, or is for use in your business only internally, on a confidential basis. You may make such limited number of duplicates of any output, both in machine-readable or hard copy form, as may be reasonable for these purposes only. Nothing herein shall authorize you to create any database, directorydirectory, or hard copy publication of or from the databases, whether for internal or external distribution or use.</p>
            <p><strong>7. Miscellaneous.</strong></p>
            <p>This Agreement shall all be governed and construed in accordance with the laws of United Kingdom applicable to agreements made and to be performed in United Kingdom. You agree that any legal action or proceeding between http://www.myeasygoals.com and you for any purpose concerning this Agreement or the parties" obligations hereunder shall be brought exclusively in a federal or state court of competent jurisdiction sitting in United Kingdom. Any cause of action or claim you may have with respect to the Service must be commenced within one (1) year after the claim or cause of action arises or such claim or cause of action is barred. http://www.myeasygoals.com"s failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this Agreement. http://www.myeasygoals.com may assign its rights and duties under this Agreement to any party at any time without notice to you.</p>
            <p><strong>Any rights not expressly granted herein are reserved.</strong></p>   '
        ]);

        UserGuide::create([
            'user_guide' => '<p><strong>My Easy Goals&trade; </strong>is a subscription-based app that provides a simple system which allows users to erase the unconscious blocks preventing them from achieving any personal or professional goals in less than two minutes.</p>
            <p>It does this by utilizing a cutting-edge audio technology known as Neuro-Accelerated Conditioning&trade;.</p>
            <p>By using the<strong> My Easy Goals&trade;</strong> system you can direct your mind to release the thoughts, feelings, and behavior which is blocking you from easily achieving virtually any goal or objective.</p>
            <p><strong>My Easy Goals&trade;</strong> is the brainchild of trainer, coach, author, and personal growth pioneer T. D. McKenzie. Mr. McKenzie is the founder and CEO of TD McKenzie Coaching and the creator of Neuro-Accelerated Conditioning&trade;.</p>
            <p><br>The My Easy Goals&trade; process is ultra simple and involves three simple steps:</p>
            <p>Type your goal into the Goal Box.<br>1. Click the permission button.<br>1. Click on the audio play button and listen to it until it ends (its only 60 seconds).</p>
            <p>Once the above three steps have been completed you simply list all the action steps necessary to make your goal a reality in the drop down menu in the &ldquo;Master Goal List&rdquo; section within the app that can be accessed from the main menu.</p>
            <p>You will discover that the implementation of the action steps is far easier than before.</p>
            <p>In addition to using the app on your main goals, you can use it for simple day to day tasks you&rsquo;ve been putting off.</p>
            <p>In order to take advantage of the full resources of the app, it"s important to be clear about what it is you wish to create.</p>
            <p>For a goal to work effectively with the app you need to develop a specific written objective with the following elements:</p>
            <p>Leave out the word &ldquo;I&rdquo; but make it present tense.</p>
            <p>Most goal setting books advise you to word the goal by making it personal by including &ldquo;I&rdquo; at the beginning, however, as we are using a conditioning audio that already assigns the goal to you this isn&rsquo;t necessary.</p>
            <p>In all your goal statements all that&rsquo;s required is that you word the goal as an outcome you want to achieve in your reality as a fact.</p>
            <p>Here&rsquo;s an example:</p>
            <p>Wrong<br>I now have over $100,000 in my bank account.</p>
            <p>Right<br>Have over $100,000 in my bank account</p>
            <p>Include only what you wish to create.</p>
            <p>It is very important for you to create goals that focus only on what you desire and not what you are trying to avoid.</p>
            <p>The reason for this is that you communicate with your mind primarily through the use of pictures and images. For instance, for the next five seconds I do not want you to think about clowns with big red noses.</p>
            <p>Now what is the picture that just passed through your mind?</p>
            <p>By including only what you wish to achieve in the goal, the audio works far more effectively. You are sending a clear instruction to your mind about what it is you wish to create.</p>
            <p>Wrong<br>I am no longer struggling to pay off my credit card debts.</p>
            <p>Right<br>All outstanding balances on my credit cards are now paid in full.</p>
            <p>Be specific, but allow for more.</p>
            <p>Another interesting thing about the mind is that it works best when dealing with specifics. Vague goals of any kind will usually be ignored, as they are not measurable in any way.</p>
            <p>Surprisingly, this is one mistake many people continue to make when setting goals, and consequently they end up experiencing one failure after another.</p>
            <p>If you truly wish to "get there" it"s vitally important for you to first establish where your "there" is.</p>
            <p>It"s not enough to say you wish to lose weight, get a better job, drive a new car, or meet someone special. You must clarify your goal with specifics, whilst allowing room for the possibility of even more.</p>
            <p>Wrong<br>I now live in a larger home.</p>
            <p>Right<br>Own a beautiful house with five bedrooms, parking for three cars, and over two acres of land.</p>
            <p>Don"t include the "how&rsquo;.<br>When setting your goal leave out what you think you will have to do in order to achieve it. This is a common mistake; the reason for this is simple and it"s called fear.</p>
            <p>You may become a little anxious as soon as you start to even think of your goal, which is natural, especially if it means you will have to move out of your comfort zone.</p>
            <p>The beauty of the app is that it forces you to ONLY focus on the end result. The &ldquo;how&rdquo; will become more apparent after you are clear on your outcome.</p>
            <p>Wrong<br>I will reduce my weight from 195 pounds to 175 pounds by exercising four times per week, eating a maximum of 1,800 calories, taking three supplements, and drinking two liters of water per day.</p>
            <p>Right<br>Weigh 175 pounds with 8% body fat.</p>
            <p>Focus on a single goal in each statement.</p>
            <p>Keep your goal focused on a single area of your life. This makes it easier for you to maintain your focus on what you wish to achieve and, again, makes the app much more effective.</p>
            <p>People sometimes try to cram everything into "one" goal because of the mistaken belief there is so much going wrong in their lives and they need to fix everything.</p>
            <p>You will learn that by setting and achieving specific goals, other areas of your life will gradually start to resolve themselves without your intervention.</p>
            <p>Wrong<br>I now have a wonderful new job that pays me $80,000 per year, which allows me to afford a $250,000 home, together with a brand-new BMW my new girlfriend adores.</p>
            <p>Right<br>Have a job I enjoy that pays me over $80,000 per year.</p>
            <p>Sample Goals<br>If you are still having difficulty with wording your goals, you can use the sample goals that can be accessed from the main menu.</p>
            <p>There are many productivity apps on the market that overly confuse the achievement of goals, by adding too many screens and functionalities.</p>
            <p>What I want you to do to get the most from the MY Easy Goals&trade; is to simply the two simple steps here:</p>
            <p>- Weekly<br>Once a week, preferably on a weekend, go somewhere you will not be disturbed for 30 minutes and in a journal, notepad, or the Assorted tasks page within the app, make a list of everything you have to do that not related to your goals or action steps.</p>
            <p>Once you have your list, go to the next step.</p>
            <p>- Daily<br>On a daily basis select three action steps from your major goals and three tasks from your miscellaneous tasks and add them to your daily to do list to be completed that day.</p>
            <p>Adopting this simple strategy will allow you to make consistent progress on your goals as well as your everyday tasks.</p>
            <p>To ensure you follow through with system, I have detailed two goals you can use in on the release section of the app.</p>
            <p>Create a master list of all miscellaneous tasks every week.<br>Select 6 items every day from major goals action steps and miscellaneous tasks and complete them.</p>'
        ]);
    }
}
